# Generated by Django 4.2.7 on 2023-11-23 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quarto', '0001_initial'),
        ('hospedagem', '0002_alter_hospedagem_cliente_delete_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospedagem',
            name='quarto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quarto.quarto'),
        ),
        migrations.DeleteModel(
            name='Quarto',
        ),
    ]
